commerce_payment.commerce_payment_gateway.plugin.gmo_token:
  type: commerce_payment_gateway_configuration
  mapping:
    shop_id:
      type: string
      label: 'Shop ID'
    shop_pass:
      type: string
      label: 'Shop password'
